[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["pnpm install --prod=false"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node dist/server.js"
