[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm build"]

[start]
cmd = "pnpm db:push && node dist/server.js"
